export * from './BannerImage'
export * from './Logo'
export * from './TypegraphiesComp'
export * from './Inputsprops'
export * from './Buttonsprops'
export * from './CardComponente'
export { default as AvatarComp } from './AvatarListComp'
export { default as FormularioComponentes } from './FormularioComp'
export { default as TableComp } from './TableComponente'

export { default as Header } from './Header'
export { default as Graphie } from './GraphiesComp'
