export { default as Cadastro } from './Registration'
export { default as Home } from './Home'
export { default as Leads } from './Leads'
export { default as Login } from './Login'
export { default as Perfil } from './Perfil'
